#!/bin/sh

set -eu

TARGET_NAME="${TARGET_NAME:-BlobBackgroundView}"
PACKAGE_PATH="${PACKAGE_PATH:-.}"
DERIVED_DATA_PATH="${DERIVED_DATA_PATH:-$PACKAGE_PATH/.build/docc-derived-data}"
DOCC_ARCHIVE_PATH="${DOCC_ARCHIVE_PATH:-$PACKAGE_PATH/$TARGET_NAME.doccarchive}"
DOCS_OUTPUT_PATH="${DOCS_OUTPUT_PATH:-$PACKAGE_PATH/docs}"
HOSTING_BASE_PATH="${HOSTING_BASE_PATH:-$TARGET_NAME}"
DESTINATION="${DESTINATION:-generic/platform=iOS}"

DOCC="$(xcrun --find docc)"

HOSTING_BASE_PATH="$(printf '%s' "$HOSTING_BASE_PATH" | sed -E 's#^[[:space:]/]+##; s#[[:space:]/]+$##')"
if [ -z "$HOSTING_BASE_PATH" ]; then
  HOSTING_BASE_PATH="$TARGET_NAME"
fi

rm -rf "$DERIVED_DATA_PATH" "$DOCC_ARCHIVE_PATH" "$DOCS_OUTPUT_PATH"

xcodebuild docbuild \
  -scheme "$TARGET_NAME" \
  -destination "$DESTINATION" \
  -derivedDataPath "$DERIVED_DATA_PATH" \
  -skipMacroValidation

FOUND_ARCHIVE="$(find "$DERIVED_DATA_PATH" -name "$TARGET_NAME.doccarchive" -type d -print -quit)"

if [ -z "$FOUND_ARCHIVE" ]; then
  echo "error: no DocC archive found for $TARGET_NAME" >&2
  exit 1
fi

cp -R "$FOUND_ARCHIVE" "$DOCC_ARCHIVE_PATH"

"$DOCC" process-archive \
  transform-for-static-hosting "$DOCC_ARCHIVE_PATH" \
  --output-path "$DOCS_OUTPUT_PATH" \
  --hosting-base-path "$HOSTING_BASE_PATH"

if [ ! -f "$DOCS_OUTPUT_PATH/index.html" ]; then
  echo "error: DocC static hosting did not create $DOCS_OUTPUT_PATH/index.html" >&2
  exit 1
fi

if [ ! -d "$DOCS_OUTPUT_PATH/data/documentation" ]; then
  echo "error: DocC static hosting did not create documentation data" >&2
  exit 1
fi

HOSTING_BASE_PATH="/${HOSTING_BASE_PATH#/}"
export HOSTING_BASE_PATH

perl -0pi -e '
  my $base = $ENV{"HOSTING_BASE_PATH"};
  s#href="/favicon\.ico"#href="$base/favicon.ico"#g;
  s#href="/favicon\.svg"#href="$base/favicon.svg"#g;
  s#var baseUrl = "/"#var baseUrl = "$base/"#g;
  s#src="/js/#src="$base/js/#g;
  s#href="/css/#href="$base/css/#g;
' "$DOCS_OUTPUT_PATH/index.html"

find "$DOCS_OUTPUT_PATH" -type f -name '*.js' \
  -exec perl -0pi -e 's/[ \t]+$//mg' {} +

rm -rf "$DOCC_ARCHIVE_PATH" "$DERIVED_DATA_PATH"
